<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <!-- This project is a library providing route extension methods; Host is the entry point -->
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SoftPlc.Core\SoftPlc.Core.csproj" />
    <ProjectReference Include="..\SoftPlc.S7Server\SoftPlc.S7Server.csproj" />
  </ItemGroup>

</Project>
